import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";

import QueryClientProviderWrapper from "@/components/QueryClientProviderWrapper";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Tarefa Front-end Caveo - Gabriel Logan",
    template: "%s | Tarefa Front-end Caveo - Gabriel Logan",
  },
  description: "Generated by create next app and created by Gabriel Logan",
  authors: [
    {
      name: "Gabriel Logan",
    },
  ],
  classification: "Ecommerce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProviderWrapper>
          <ToastContainer autoClose={1500} />
          {children}
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
